### ISSUE TITLE
Multiple Extensions fail to begin stream

### ISSUE THREAD

**Issue by Soggy-Pancake** [aniyomiorg/aniyomi-extensions#1670]
### Source information and language

Animension, kickassanime, kissanime.com.ru

### Steps to reproduce

Pick anime from any of the above extensions and wait

### Expected behavior

Stream loads eventually

### Actual behavior

Spinny circle

### Aniyomi version

r6147

### Android version

9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/jmir1/aniyomi/releases/latest)**
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/jmir1/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Soggy-Pancake** [comment]
Additional info:

kissanime.com.ru > after failing to start stream empty toast appears

kissanime dl > failed to bypass cloudflare

Animension dl and kickassAnime dl > list is empty error

**Comment by Secozzi** [comment]
For the _Failed to bypass Cloudflare_ error, refer to the Solving Cloudflare issues section at https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues. If it doesn't work, migrate to other sources or wait until they lower their protection.

Closing because bugs for multiple extensions are present in this single issue. Please make a separate issue for each extension.
