### ISSUE TITLE
Mangafire search not working

### ISSUE THREAD

**Issue by pavonismc** [aniyomiorg/aniyomi-extensions#2235]
### Source information

Mangafire 1.4.2

### Source language

English

### Steps to reproduce

Open the extension source and search for something you know is available

### Expected behavior

It shows a list of manga related to the search

### Actual behavior

It say nothing is available

### Aniyomi version

Preview r6151

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Secozzi** [comment]
Manga extensions aren't managed on this repo. All issues regarding manga extensions needs to go to the tachiyomi repo but since there [already an issue](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/17715) related to your problem, there's no need to create a new one. Just wait patiently until it gets fixed (or just use another extension).
