### ISSUE TITLE
Anime Base broken

### ISSUE THREAD

**Issue by Xyndra** [aniyomiorg/aniyomi-extensions#2760]
### Source information

Anime Base 13.18

### Source language

German 

### Steps to reproduce

Install
Open
~The table,~ its broken

### Expected behavior

No broken

### Actual behavior

Error

### Aniyomi version

App version: 0.15.2.0 (standard, 589054b, 118, 2024-01-13T20:47Z) Android version: 13 (SDK 33; build RMX3241_11_F.08) Android build ID: RMX3241_11_F.08 Device brand: realme Device manufacturer: realme Device name: RE513CL1 (RMX3241EEA) Device model: RMX3241 WebView: Android System WebView 120.0.6099.194

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3.10](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Pls don't just say it's broken and make everyone figure out what the actual problem is... Just a reminder for the future 🔮 😉

Anime-Base works in webview, but has currently the following issues:
- opening the Anime-Base _popular_ catalog it shows `http error 404`, same goes for the catalog search
- catalog _newest_ tab results with no results
- each episode is listed twice (sub+dub each) =>combined would be better (like Aniwave)
- Anime Library throw an error `NullPointerException: null`
