### ISSUE TITLE
HTTP 429 error 

### ISSUE THREAD

**Issue by mcdanzo** [aniyomiorg/aniyomi-extensions#3034]
### Source information

999Hentai

### Source language

English 

### Steps to reproduce

HTTP 429, check website in WebV
![IMG_20240310_061247](https://github.com/aniyomiorg/aniyomi-extensions/assets/162848215/1c328cb5-06cb-4e8f-923c-940daf048a12)
iew

### Expected behavior

It's start to happen recently 

### Actual behavior

Now it's not working anymore 

### Aniyomi version

0.15.2.4

### Android version

Android 10

### Other details

I don't know much about it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.2.4](https://github.com/aniyomiorg/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/aniyomiorg/aniyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Joker2583** [comment]
Tachiyomi has removed it's extension list.
Aniyomi manages anime list.
You will have to use third party manga extensions at your own risk.
Try this
## Guide
https://keiyoushi.github.io/docs/guides/getting-started#adding-the-extension-repo

Make sure to also give the repo a star at https://github.com/keiyoushi/extensions

After following the above guide.
1. **UNINSTALL ALL EXISTING EXTENSIONS** (You won't get future updates otherwise). 
2. Close your app and reopen it, then reinstall all the extensions (tip: see what extensions you're missing by looking at the Browse > Migration tab)

## Source Code
https://github.com/keiyoushi/extensions-source

## Report issues/request
https://github.com/keiyoushi/extensions-source/issues/new/choose

**Comment by Secozzi** [comment]
@Joker2583 don't share third party repositories

**Comment by Secozzi** [comment]
This is not an extension we manage
