### ISSUE TITLE
[Feature Request] hanime.tv: Merge episodes

### ISSUE THREAD

**Issue by K4Z3R0** [aniyomiorg/aniyomi-extensions#633]
## What feature should be added to this source?

Make hanime.tv's separate episode listings merge into one, for example, there's **Hentai 1** and **Hentai 2**, but make them merge into one title **Hentai** with two episodes inside.

_I hope you understand because I'm terrible at explaining things._

**Comment by KazKaz90** [comment]
I'm not sure if it's possible to implement because that's how they are on the hanime.tv website, but there's an [app that made it](![Screenshot_20220708-133239.png](https://user-images.githubusercontent.com/90075041/177923742-17ba0d21-e1d3-42b6-bc1f-c1455aa5c9fc.png), merging the episodes into one hanime title, but I wanted it on Aniyomi.

**Comment by KazKaz90** [comment]
I'm not sure if it's possible to implement because that's how they are on the hanime.tv website, but there's an [app that made it](https://user-images.githubusercontent.com/90075041/177924016-334d07d2-f483-4fc9-9904-cedd67293ef3.png), merging the episodes into one hanime title, but I wanted it on Aniyomi.

**Comment by stam76** [comment]
Can u share app link @KazKaz90

**Comment by KazKaz90** [comment]
> Can u share app link @KazKaz90 

@stam76 
https://github.com/Jacekun/CloudStream-3XXX
